[project]
name = "voltguard"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "uv>=0.9.25",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.18.0",
    "pytest>=9.0.2",
    "ruff>=0.9.2",
    "pyright>=1.1.392",
]
